
" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Markdown syntax highlighting for Vim	
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
nmap <leader>md :%! ~/.vim/bin/Markdown.pl --html4tags <cr>
  
"alignment
Plug 'junegunn/vim-easy-align'

" Visualize and traverse your undo tree
Plug 'sjl/gundo.vim'

Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
	
Plug 'scrooloose/syntastic'
Plug 'morhetz/gruvbox'

"editor 
" Tab completion
Plug 'ervandew/supertab'

" EasyMotion - Allows <leader><leader>(b|e) to jump to (b)eginning or (end)
" of words.
Plug 'easymotion/vim-easymotion'

Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

" file manager
Plug 'scrooloose/nerdtree'
Plug 'jistr/vim-nerdtree-tabs'


"{{{ airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
"}}}

"{{{ ctrlp
" A buffer/file/mru/tag explorer with fuzzy text matching
Plug 'kien/ctrlp.vim'
"}}}

"{{{ gitgutter
"shows a git diff in the 'gutter' (sign column) 
Plug 'airblade/vim-gitgutter'
" }}}

"{{{ LaTeX 
Plug 'lervag/vimtex'
Plug 'LaTeX-Box-Team/LaTeX-Box'
"}}} 

" c/c++
" Initialize plugin system
call plug#end()


"---package configuration---

" gundo{{{
":GundoToggle

" }}}

" ctrlp {{{
set wildignore+=*/tmp/*,*.swp,*.zip,*.tar.gz 
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(out|o|mp4|pdf|epub|chm|png|jpg|gif)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }
let g:ctrlp_working_path_mode = 'ra'
"}}}

" airline {{{
let g:airline_powerline_fonts = 1
let g:airline_theme="zenburn"
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
" unicode symbols
let g:airline_left_sep = '»'
"let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
"let g:airline_right_sep = '◀'
"let g:airline_symbols.linenr = '␊'
"let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
"let g:airline_symbols.paste = 'Þ'
"let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'
" }}}

"syntastic {{{
let g:syntastic_error_symbol='✗'
let g:syntastic_warning_symbol='⚠'
let g:syntastic_enable_highlighting = 1
let g:syntastic_stl_format = '[%E{Err: %fe #%e}%B{, }%W{Warn: %fw #%w}]'
let g:syntastic_php_checkers = ['php']
" }}}

"配合使用增强版命令重复
"for repeat -> enhance surround.vim, . to repeat command
" surround {{{
"命令 cs ds yss
" helps delete and surround brackets
"ds(delete surroundings),
"cs(change surroundings),
"cst(change surroundings to ")
"ys(yank surround)
"ysw(ys with ) 光标下位置开始
"ysiw(ys it with ) 单词
" }}}

" colorscheme
set background=dark
colorscheme gruvbox
let g:gruvbox_contrast_dark="hard"


"let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'

" Ultisnips {{{
let g:UltiSnipsExpandTrigger = '<TAB>'
" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit='vertical'
let g:UltiSnipsSnippetsDir=$HOME.'/.vim/plugged/vim-snippets/UltiSnips'

" }}}

"---generel configuration---
filetype on
filetype plugin indent on
syntax on

set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1  "encoding dectection
set tabstop=4 shiftwidth=4 softtabstop=4 noexpandtab
set history=5000
set wrap
let &showbreak = '↪'
set t_ti= t_te=  " Disable the \"clear\" after you close

if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
endif

